# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminArea.ui'
#
# Created: Fri Sep 19 15:01:42 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_adminWindow(object):
    def setupUi(self, adminWindow):
        adminWindow.setObjectName(_fromUtf8("adminWindow"))
        adminWindow.setEnabled(True)
        adminWindow.resize(745, 514)
        adminWindow.setMinimumSize(QtCore.QSize(329, 218))
        adminWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/images/48x48/registron.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        adminWindow.setWindowIcon(icon)
        adminWindow.setWindowOpacity(1.0)
        adminWindow.setStyleSheet(_fromUtf8("background: rgb(10, 80, 111);"))
        self.centralwidget = QtGui.QWidget(adminWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 721, 451))
        self.tabWidget.setStyleSheet(_fromUtf8("color:white;background: rgb(10, 80, 111);"))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.indexTab = QtGui.QWidget()
        self.indexTab.setObjectName(_fromUtf8("indexTab"))
        self.schoolName = QtGui.QTextEdit(self.indexTab)
        self.schoolName.setGeometry(QtCore.QRect(20, 40, 681, 31))
        self.schoolName.setStyleSheet(_fromUtf8("background: white;color:black;"))
        self.schoolName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.schoolName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.schoolName.setObjectName(_fromUtf8("schoolName"))
        self.schoolNameLabel = QtGui.QLabel(self.indexTab)
        self.schoolNameLabel.setGeometry(QtCore.QRect(20, 15, 161, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.schoolNameLabel.setFont(font)
        self.schoolNameLabel.setObjectName(_fromUtf8("schoolNameLabel"))
        self.addStudentLabel = QtGui.QLabel(self.indexTab)
        self.addStudentLabel.setGeometry(QtCore.QRect(20, 130, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.addStudentLabel.setFont(font)
        self.addStudentLabel.setObjectName(_fromUtf8("addStudentLabel"))
        self.surnameLabel = QtGui.QLabel(self.indexTab)
        self.surnameLabel.setGeometry(QtCore.QRect(20, 160, 81, 16))
        self.surnameLabel.setObjectName(_fromUtf8("surnameLabel"))
        self.othernamesLabel = QtGui.QLabel(self.indexTab)
        self.othernamesLabel.setGeometry(QtCore.QRect(360, 160, 101, 16))
        self.othernamesLabel.setObjectName(_fromUtf8("othernamesLabel"))
        self.textEdit = QtGui.QTextEdit(self.indexTab)
        self.textEdit.setGeometry(QtCore.QRect(20, 180, 311, 31))
        self.textEdit.setStyleSheet(_fromUtf8("background:white;color:black;"))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.textEdit_2 = QtGui.QTextEdit(self.indexTab)
        self.textEdit_2.setGeometry(QtCore.QRect(360, 180, 341, 31))
        self.textEdit_2.setStyleSheet(_fromUtf8("background:white;color:black;"))
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.studentsDeptLabel = QtGui.QLabel(self.indexTab)
        self.studentsDeptLabel.setGeometry(QtCore.QRect(20, 230, 171, 16))
        self.studentsDeptLabel.setObjectName(_fromUtf8("studentsDeptLabel"))
        self.imageDropLabel = QtGui.QLabel(self.indexTab)
        self.imageDropLabel.setGeometry(QtCore.QRect(20, 300, 641, 16))
        self.imageDropLabel.setObjectName(_fromUtf8("imageDropLabel"))
        self.textEdit_3 = QtGui.QTextEdit(self.indexTab)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 250, 681, 31))
        self.textEdit_3.setStyleSheet(_fromUtf8("background:white;color:black;"))
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.textEdit_4 = QtGui.QTextEdit(self.indexTab)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 330, 681, 31))
        self.textEdit_4.setStyleSheet(_fromUtf8("background:white;color:black;"))
        self.textEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_4.setObjectName(_fromUtf8("textEdit_4"))
        self.schoolNameBtn = QtGui.QPushButton(self.indexTab)
        self.schoolNameBtn.setGeometry(QtCore.QRect(560, 80, 141, 31))
        self.schoolNameBtn.setStyleSheet(_fromUtf8("background: rgb(10, 80, 111);"))
        self.schoolNameBtn.setObjectName(_fromUtf8("schoolNameBtn"))
        self.pushButton_2 = QtGui.QPushButton(self.indexTab)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 380, 141, 31))
        self.pushButton_2.setStyleSheet(_fromUtf8("background: rgb(10, 80, 111);"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.tabWidget.addTab(self.indexTab, _fromUtf8(""))
        self.studentsTab = QtGui.QWidget()
        self.studentsTab.setObjectName(_fromUtf8("studentsTab"))
        self.label_7 = QtGui.QLabel(self.studentsTab)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 251, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.scrollArea = QtGui.QScrollArea(self.studentsTab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 40, 201, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 197, 357))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_8 = QtGui.QLabel(self.studentsTab)
        self.label_8.setGeometry(QtCore.QRect(240, 40, 121, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.textEdit_5 = QtGui.QTextEdit(self.studentsTab)
        self.textEdit_5.setGeometry(QtCore.QRect(240, 60, 451, 31))
        self.textEdit_5.setStyleSheet(_fromUtf8("background: white;color:black;"))
        self.textEdit_5.setObjectName(_fromUtf8("textEdit_5"))
        self.label_9 = QtGui.QLabel(self.studentsTab)
        self.label_9.setGeometry(QtCore.QRect(240, 180, 121, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.textEdit_6 = QtGui.QTextEdit(self.studentsTab)
        self.textEdit_6.setGeometry(QtCore.QRect(240, 200, 451, 31))
        self.textEdit_6.setStyleSheet(_fromUtf8("background: white;color:black;"))
        self.textEdit_6.setObjectName(_fromUtf8("textEdit_6"))
        self.textEdit_7 = QtGui.QTextEdit(self.studentsTab)
        self.textEdit_7.setGeometry(QtCore.QRect(240, 270, 451, 31))
        self.textEdit_7.setStyleSheet(_fromUtf8("background: white;color:black;"))
        self.textEdit_7.setObjectName(_fromUtf8("textEdit_7"))
        self.label_10 = QtGui.QLabel(self.studentsTab)
        self.label_10.setGeometry(QtCore.QRect(240, 250, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton_3 = QtGui.QPushButton(self.studentsTab)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 320, 131, 31))
        self.pushButton_3.setStyleSheet(_fromUtf8("background: rgb(10, 80, 111); color: white;"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.textEdit_9 = QtGui.QTextEdit(self.studentsTab)
        self.textEdit_9.setGeometry(QtCore.QRect(240, 130, 451, 31))
        self.textEdit_9.setStyleSheet(_fromUtf8("background: white;color:black;"))
        self.textEdit_9.setObjectName(_fromUtf8("textEdit_9"))
        self.label_12 = QtGui.QLabel(self.studentsTab)
        self.label_12.setGeometry(QtCore.QRect(240, 110, 121, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.tabWidget.addTab(self.studentsTab, _fromUtf8(""))
        self.coursesTab = QtGui.QWidget()
        self.coursesTab.setObjectName(_fromUtf8("coursesTab"))
        self.tabWidget.addTab(self.coursesTab, _fromUtf8(""))
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName(_fromUtf8("settingsTab"))
        self.label_11 = QtGui.QLabel(self.settingsTab)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.textEdit_8 = QtGui.QTextEdit(self.settingsTab)
        self.textEdit_8.setGeometry(QtCore.QRect(10, 40, 681, 31))
        self.textEdit_8.setStyleSheet(_fromUtf8("background:white; color: black;"))
        self.textEdit_8.setObjectName(_fromUtf8("textEdit_8"))
        self.pushButton_4 = QtGui.QPushButton(self.settingsTab)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 80, 141, 31))
        self.pushButton_4.setStyleSheet(_fromUtf8("background: rgb(10, 80, 111);color:white;"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.tabWidget.addTab(self.settingsTab, _fromUtf8(""))
        adminWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(adminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAdministrators = QtGui.QMenu(self.menubar)
        self.menuAdministrators.setObjectName(_fromUtf8("menuAdministrators"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        adminWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(adminWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        adminWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(adminWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionDocumentation = QtGui.QAction(adminWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionAbout = QtGui.QAction(adminWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionCredits = QtGui.QAction(adminWindow)
        self.actionCredits.setObjectName(_fromUtf8("actionCredits"))
        self.actionSignIn = QtGui.QAction(adminWindow)
        self.actionSignIn.setObjectName(_fromUtf8("actionSignIn"))
        self.actionLicense = QtGui.QAction(adminWindow)
        self.actionLicense.setObjectName(_fromUtf8("actionLicense"))
        self.actionAdmin_Logout = QtGui.QAction(adminWindow)
        self.actionAdmin_Logout.setObjectName(_fromUtf8("actionAdmin_Logout"))
        self.menuMenu.addAction(self.actionQuit)
        self.menuMenu.addSeparator()
        self.menuAdministrators.addAction(self.actionAdmin_Logout)
        self.menuAdministrators.addSeparator()
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionCredits)
        self.menuHelp.addAction(self.actionLicense)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAdministrators.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(adminWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(adminWindow)

    def retranslateUi(self, adminWindow):
        adminWindow.setWindowTitle(QtGui.QApplication.translate("adminWindow", "Registron Administrator", None, QtGui.QApplication.UnicodeUTF8))
        self.schoolNameLabel.setText(QtGui.QApplication.translate("adminWindow", "School Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.addStudentLabel.setText(QtGui.QApplication.translate("adminWindow", "Add Student:", None, QtGui.QApplication.UnicodeUTF8))
        self.surnameLabel.setText(QtGui.QApplication.translate("adminWindow", "Surname:", None, QtGui.QApplication.UnicodeUTF8))
        self.othernamesLabel.setText(QtGui.QApplication.translate("adminWindow", "Other names:", None, QtGui.QApplication.UnicodeUTF8))
        self.studentsDeptLabel.setText(QtGui.QApplication.translate("adminWindow", "Student\'s Department:", None, QtGui.QApplication.UnicodeUTF8))
        self.imageDropLabel.setText(QtGui.QApplication.translate("adminWindow", "Image (drop a 128x128 image in the folder resources/images/128x128 and put the file name here):", None, QtGui.QApplication.UnicodeUTF8))
        self.schoolNameBtn.setText(QtGui.QApplication.translate("adminWindow", "Save School Name", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("adminWindow", "Add Student", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.indexTab), QtGui.QApplication.translate("adminWindow", "School and Students", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.indexTab), QtGui.QApplication.translate("adminWindow", "Adjust settings of school and settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("adminWindow", "Click on student ID to edit profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("adminWindow", "Student Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("adminWindow", "Department:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("adminWindow", "Image file name:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("adminWindow", "Update Record", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("adminWindow", "Campus ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.studentsTab), QtGui.QApplication.translate("adminWindow", "Manage Students", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.coursesTab), QtGui.QApplication.translate("adminWindow", "Manage Courses", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.coursesTab), QtGui.QApplication.translate("adminWindow", "Add and Edit School Courses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("adminWindow", "Change Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("adminWindow", "Update Password", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), QtGui.QApplication.translate("adminWindow", "Setttings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("adminWindow", "Application", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdministrators.setTitle(QtGui.QApplication.translate("adminWindow", "Administrator", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("adminWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("adminWindow", "Quit registron", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("adminWindow", "Exit this program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("adminWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("adminWindow", "Online Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setShortcut(QtGui.QApplication.translate("adminWindow", "Ctrl+?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("adminWindow", "About Registron", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("adminWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCredits.setText(QtGui.QApplication.translate("adminWindow", "Credits", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCredits.setShortcut(QtGui.QApplication.translate("adminWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSignIn.setText(QtGui.QApplication.translate("adminWindow", "Manage Accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicense.setText(QtGui.QApplication.translate("adminWindow", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdmin_Logout.setText(QtGui.QApplication.translate("adminWindow", "Admin Logout", None, QtGui.QApplication.UnicodeUTF8))

import app_rc
