# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Oct 12 00:01:50 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(745, 514)
        MainWindow.setMinimumSize(QtCore.QSize(329, 218))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/images/48x48/registron.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet(_fromUtf8("background: rgb(10, 80, 111);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.registronLabel = QtGui.QLabel(self.centralwidget)
        self.registronLabel.setGeometry(QtCore.QRect(250, 20, 261, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.registronLabel.setFont(font)
        self.registronLabel.setStyleSheet(_fromUtf8("color: white;"))
        self.registronLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.registronLabel.setObjectName(_fromUtf8("registronLabel"))
        self.registronDesc = QtGui.QLabel(self.centralwidget)
        self.registronDesc.setGeometry(QtCore.QRect(220, 180, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registronDesc.setFont(font)
        self.registronDesc.setStyleSheet(_fromUtf8("color: white"))
        self.registronDesc.setAlignment(QtCore.Qt.AlignCenter)
        self.registronDesc.setObjectName(_fromUtf8("registronDesc"))
        self.enterMatricLabel = QtGui.QLabel(self.centralwidget)
        self.enterMatricLabel.setGeometry(QtCore.QRect(210, 230, 341, 31))
        self.enterMatricLabel.setStyleSheet(_fromUtf8("color:white"))
        self.enterMatricLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.enterMatricLabel.setObjectName(_fromUtf8("enterMatricLabel"))
        self.proceedBtn = QtGui.QPushButton(self.centralwidget)
        self.proceedBtn.setGeometry(QtCore.QRect(270, 330, 231, 41))
        self.proceedBtn.setStyleSheet(_fromUtf8("background: rgb(10, 80, 111); color: white;"))
        self.proceedBtn.setObjectName(_fromUtf8("proceedBtn"))
        self.invalidID = QtGui.QLabel(self.centralwidget)
        self.invalidID.setEnabled(True)
        self.invalidID.setGeometry(QtCore.QRect(620, -10, 121, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.invalidID.setFont(font)
        self.invalidID.setStyleSheet(_fromUtf8("color: red;"))
        self.invalidID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.invalidID.setObjectName(_fromUtf8("invalidID"))
        self.matricInput = QtGui.QLineEdit(self.centralwidget)
        self.matricInput.setGeometry(QtCore.QRect(230, 280, 301, 31))
        self.matricInput.setStyleSheet(_fromUtf8("background:white;color: black;"))
        self.matricInput.setAlignment(QtCore.Qt.AlignCenter)
        self.matricInput.setObjectName(_fromUtf8("matricInput"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 21))
        self.menubar.setStyleSheet(_fromUtf8("color:white;"))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAdministrators = QtGui.QMenu(self.menubar)
        self.menuAdministrators.setObjectName(_fromUtf8("menuAdministrators"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionCredits = QtGui.QAction(MainWindow)
        self.actionCredits.setObjectName(_fromUtf8("actionCredits"))
        self.actionSignIn = QtGui.QAction(MainWindow)
        self.actionSignIn.setObjectName(_fromUtf8("actionSignIn"))
        self.actionLicense = QtGui.QAction(MainWindow)
        self.actionLicense.setObjectName(_fromUtf8("actionLicense"))
        self.menuMenu.addAction(self.actionQuit)
        self.menuMenu.addSeparator()
        self.menuAdministrators.addAction(self.actionSignIn)
        self.menuAdministrators.addSeparator()
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionCredits)
        self.menuHelp.addAction(self.actionLicense)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAdministrators.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Registron", None, QtGui.QApplication.UnicodeUTF8))
        self.registronLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Registron student program", None, QtGui.QApplication.UnicodeUTF8))
        self.registronLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/images/resources/images/80x80/registron.png\"/></p><p>Registron</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.registronDesc.setText(QtGui.QApplication.translate("MainWindow", "Student\'s course registration program", None, QtGui.QApplication.UnicodeUTF8))
        self.enterMatricLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Enter your Matriculation Number/Campus ID:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.proceedBtn.setText(QtGui.QApplication.translate("MainWindow", "Proceed to course registration", None, QtGui.QApplication.UnicodeUTF8))
        self.invalidID.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/images/resources/images/48x48/stop.png\"/></p><p align=\"center\">ACCESS DENIED</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Application", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdministrators.setTitle(QtGui.QApplication.translate("MainWindow", "Administrator", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit registron", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Exit this program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "Online Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About Registron", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCredits.setText(QtGui.QApplication.translate("MainWindow", "Credits", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCredits.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSignIn.setText(QtGui.QApplication.translate("MainWindow", "Manage Accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicense.setText(QtGui.QApplication.translate("MainWindow", "License", None, QtGui.QApplication.UnicodeUTF8))

import app_rc
